### ISSUE TITLE
Can't install phrydy (issues with versioneer.py)

### ISSUE THREAD

**Issue by trustosas** [Josef-Friedrich/phrydy#2]
~ $ pip install phrydy
Collecting phrydy
  Using cached phrydy-3.2.0.tar.gz (43 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      /data/data/com.termux/files/usr/tmp/pip-install-caw1sbok/phrydy_7ee402d13dc7494b89a590db9a5685e1/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-rrta5y5f/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-rrta5y5f/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-rrta5y5f/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 516, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-rrta5y5f/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 24, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-install-caw1sbok/phrydy_7ee402d13dc7494b89a590db9a5685e1/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-install-caw1sbok/phrydy_7ee402d13dc7494b89a590db9a5685e1/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-install-caw1sbok/phrydy_7ee402d13dc7494b89a590db9a5685e1/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by trustosas** [comment]
Similar issue and a possible fix [here](https://github.com/pydata/pandas-datareader/issues/969#issuecomment-1786843855).

**Comment by Josef-Friedrich** [comment]
Thank you for reporting this. I must release a new version on PiPy. In the main branch the versioneer.py is already removed. 

```
pip install git+https://github.com/Josef-Friedrich/phrydy.git
```

should install the package.

**Comment by trustosas** [comment]
Thanks! This works.

**Comment by Josef-Friedrich** [comment]
New release: https://pypi.org/project/phrydy/3.2.2/

Unfortunately, Phrydy is not compatible with py3.13 (dependency mediafile is not ready).
